// Generated by `cf migrate wrangler.jsonc --bundler wrangler` (cf 1.0.0-beta.9), then hand-edited (SQ-255; US-8
// contract Decisions 1 and 6). This is the `cf build` / `cf deploy` config for the main Worker.
//
// `--mode` selects one of two shapes:
//   - production: wrangler.jsonc merged with the private overlay .dev/wrangler.deploy.jsonc by the SAME
//     validateOverlayKeys() + mergeOverlay() the injector uses to write wrangler.production.jsonc
//     (scripts/lib/overlay-merge.mjs), deployed as bv-dns-security-mcp. A missing or invalid overlay THROWS.
//   - every other mode, including none (a bare `cf build` / `cf deploy`): the public wrangler.jsonc shape only,
//     deployed as bv-dns-security-mcp-dev, so a deploy that forgets `--mode production` creates a separate
//     Worker instead of stripping production's private bindings. Its Durable Object bindings and tail consumer
//     point at the -dev Worker itself, never at production.
//
// Binding NAMES are written out below so `cf workers types` can infer them. Every VALUE (IDs, database, bucket,
// queue and dataset names, service targets, var values) comes from wrangler.jsonc or the overlay and is never
// written here. A binding in either file that this config does not declare THROWS instead of being dropped, with
// two exceptions that pass through untyped because their names are open-ended: vars, and the per-tenant
// `TENANT_DB_*` D1 bindings (named after tenants by scripts/tenants/provision-tenant.mjs, resolved by name in
// src/tenants/tenant-resolver.ts).
//
// wrangler.jsonc stays: vitest (`wrangler.configPath`), `wrangler types` (npm run typecheck) and the injector
// read it. Parity with it and with the injector is pinned by test/audits/cloudflare-config.node.test.ts.
// `upload_source_maps` is a tooling setting and lives in wrangler.config.ts.
import { bindings, defineConfig, exports, triggers } from 'cf/config';
import type { QueueConsumerTrigger, ScheduledTrigger, WorkerConfig } from 'cf/config';
import { existsSync, readFileSync } from 'node:fs';
import { REQUIRED_PRODUCTION_VARS, mergeOverlay, parseJsonc, validateOverlayKeys } from './scripts/lib/overlay-merge.mjs';

export const PRODUCTION_WORKER_NAME = 'bv-dns-security-mcp';
export const NON_PRODUCTION_WORKER_NAME = 'bv-dns-security-mcp-dev';
export const PRODUCTION_OVERLAY_PATH = '.dev/wrangler.deploy.jsonc';
/** Probe hook: evaluate production mode against another overlay file (e.g. a temp copy of the example). Deploys never set it. */
export const OVERLAY_PATH_ENV = 'BV_DEPLOY_OVERLAY_PATH';
const PUBLIC_CONFIG_PATH = 'wrangler.jsonc';
const TENANT_DB_PREFIX = 'TENANT_DB_';

// eslint-disable-next-line @typescript-eslint/no-explicit-any -- wrangler-shaped JSONC, validated field by field below
type Wrangler = Record<string, any>;
type Binding = NonNullable<WorkerConfig['env']>[string];

/** wrangler.jsonc keys rendered literally below rather than read: the overlay cannot change them (OVERLAY_PUBLIC_OWNED_KEYS). */
const LITERAL_KEYS = [
	'$schema',
	'name',
	'main',
	'compatibility_date',
	'compatibility_flags',
	'upload_source_maps',
	'limits',
	'observability',
	'tail_consumers',
	'migrations',
];
/** Keys whose entries are read and rendered by the reader. Any other key fails closed. */
const READ_KEYS = [
	'vars',
	'services',
	'durable_objects',
	'triggers',
	'kv_namespaces',
	'd1_databases',
	'r2_buckets',
	'analytics_engine_datasets',
	'queues',
	'secrets',
];
/** Fields each binding kind may carry. Mapped ones are rendered; preview / migration fields are local tooling, not deployed. */
const FIELDS = {
	services: ['binding', 'service', 'entrypoint', 'props'],
	durableObjects: ['name', 'class_name', 'script_name'],
	kv: ['binding', 'id', 'preview_id'],
	d1: ['binding', 'database_name', 'database_id', 'preview_database_id', 'migrations_dir', 'migrations_table'],
	r2: ['binding', 'bucket_name', 'jurisdiction', 'preview_bucket_name'],
	analytics: ['binding', 'dataset'],
	producers: ['binding', 'queue', 'delivery_delay'],
	consumers: ['queue', 'max_batch_size', 'max_batch_timeout', 'max_retries', 'dead_letter_queue', 'max_concurrency', 'retry_delay'],
};

function fail(message: string): never {
	throw new Error(`cloudflare.config.ts: ${message}`);
}

/** Drop undefined bindings (absent from this source) so cf's schema never sees them. */
function present<T extends Record<string, Binding | undefined>>(env: T): { [K in keyof T]: Exclude<T[K], undefined> } {
	return Object.fromEntries(Object.entries(env).filter(([, binding]) => binding !== undefined)) as {
		[K in keyof T]: Exclude<T[K], undefined>;
	};
}

/**
 * Looks bindings up by name in a wrangler-shaped config and renders them with the codemod's mapping (spike ledger
 * L34), recording every entry it renders so `remainder()` can refuse anything left unrendered.
 */
function createReader(source: Wrangler, workerName: string) {
	const unknownKeys = Object.keys(source).filter((key) => !LITERAL_KEYS.includes(key) && !READ_KEYS.includes(key));
	if (unknownKeys.length > 0) fail(`${unknownKeys.join(', ')} would be silently dropped; render it explicitly.`);

	const vars: Wrangler = source.vars ?? {};
	const lists = {
		services: (source.services ?? []) as Wrangler[],
		durableObjects: (source.durable_objects?.bindings ?? []) as Wrangler[],
		kv: (source.kv_namespaces ?? []) as Wrangler[],
		d1: (source.d1_databases ?? []) as Wrangler[],
		r2: (source.r2_buckets ?? []) as Wrangler[],
		analytics: (source.analytics_engine_datasets ?? []) as Wrangler[],
		producers: (source.queues?.producers ?? []) as Wrangler[],
		consumers: (source.queues?.consumers ?? []) as Wrangler[],
	};
	const secrets: string[] = source.secrets?.required ?? [];
	const rendered = new Set<unknown>();

	function take(kind: keyof typeof lists, name: string): Wrangler | undefined {
		const nameKey = kind === 'durableObjects' ? 'name' : 'binding';
		const entry = lists[kind].find((candidate) => candidate?.[nameKey] === name);
		if (entry === undefined) return undefined;
		const unknownFields = Object.keys(entry).filter((field) => !FIELDS[kind].includes(field));
		if (unknownFields.length > 0) fail(`${name} carries ${unknownFields.join(', ')}, which the cf rendering would drop.`);
		rendered.add(entry);
		return entry;
	}
	function text(name: string) {
		if (!(name in vars)) return undefined;
		if (typeof vars[name] !== 'string') fail(`var ${name} is not a string; only text vars are rendered.`);
		rendered.add(`var:${name}`);
		return bindings.text(vars[name] as string);
	}
	function d1(name: string) {
		const e = take('d1', name);
		return e && bindings.d1({ name: e.database_name, id: e.database_id });
	}
	const self = (name: string | undefined) => (name === undefined || name === source.name ? workerName : name);

	return {
		text,
		d1,
		worker(name: string) {
			const e = take('services', name);
			// `as string` keeps the inferred Env type a Fetcher; an untyped target would infer `any`.
			return e && bindings.worker({ worker: e.service as string, exportName: e.entrypoint as string | undefined, props: e.props });
		},
		durableObject(name: string) {
			const e = take('durableObjects', name);
			return e && bindings.durableObject({ worker: self(e.script_name), exportName: e.class_name as string });
		},
		kv(name: string) {
			const e = take('kv', name);
			return e && bindings.kv({ id: e.id });
		},
		r2(name: string) {
			const e = take('r2', name);
			return e && bindings.r2({ name: e.bucket_name, jurisdiction: e.jurisdiction });
		},
		analyticsEngineDataset(name: string) {
			const e = take('analytics', name);
			return e && bindings.analyticsEngineDataset({ name: e.dataset });
		},
		queue(name: string) {
			const e = take('producers', name);
			return e && bindings.queue({ name: e.queue, deliveryDelay: e.delivery_delay });
		},
		secret(name: string) {
			if (!secrets.includes(name)) return undefined;
			rendered.add(`secret:${name}`);
			return bindings.secret();
		},
		triggers(): (ScheduledTrigger | QueueConsumerTrigger)[] {
			const crons: string[] = source.triggers?.crons ?? [];
			const unknownTriggers = Object.keys(source.triggers ?? {}).filter((key) => key !== 'crons');
			if (unknownTriggers.length > 0) fail(`triggers.${unknownTriggers.join(', triggers.')} would be silently dropped.`);
			const consumers = lists.consumers.map((c) => {
				const unknownFields = Object.keys(c).filter((field) => !FIELDS.consumers.includes(field));
				if (unknownFields.length > 0)
					fail(`queue consumer ${c.queue} carries ${unknownFields.join(', ')}, which the cf rendering would drop.`);
				rendered.add(c);
				return triggers.queue({
					name: c.queue,
					maxBatchSize: c.max_batch_size,
					maxBatchTimeout: c.max_batch_timeout,
					maxRetries: c.max_retries,
					deadLetterQueue: c.dead_letter_queue,
					maxConcurrency: c.max_concurrency,
					retryDelay: c.retry_delay,
				});
			});
			return [...crons.map((schedule) => triggers.scheduled({ schedule })), ...consumers];
		},
		/**
		 * Renders the open-ended pass-throughs (vars, TENANT_DB_* D1s) and THROWS on anything else not yet rendered.
		 * Call it after every declared binding has been read. Its keys are deliberately untyped.
		 */
		remainder(): Record<never, never> {
			const extra: Record<string, Binding> = {};
			for (const name of Object.keys(vars)) if (!rendered.has(`var:${name}`)) extra[name] = text(name)!;
			for (const e of lists.d1) {
				if (!rendered.has(e) && typeof e.binding === 'string' && e.binding.startsWith(TENANT_DB_PREFIX)) extra[e.binding] = d1(e.binding)!;
			}
			const undeclared = [
				...Object.entries(lists).flatMap(([kind, list]) =>
					list.filter((e) => !rendered.has(e)).map((e) => `${kind} ${e?.binding ?? e?.name ?? e?.queue ?? JSON.stringify(e)}`),
				),
				...secrets.filter((name) => !rendered.has(`secret:${name}`)).map((name) => `secret ${name}`),
			];
			if (undeclared.length > 0) fail(`declares no binding for ${undeclared.join(', ')}; it would be silently dropped. Declare it below.`);
			return extra;
		},
	};
}

type Reader = ReturnType<typeof createReader>;

/** The public wrangler.jsonc bindings, present in every mode. */
function publicBindings(read: Reader) {
	return {
		ENABLE_OAUTH: read.text('ENABLE_OAUTH'),
		ENABLE_OWNER_OAUTH: read.text('ENABLE_OWNER_OAUTH'),
		BV_WEB_OAUTH_CONSENT_URL: read.text('BV_WEB_OAUTH_CONSENT_URL'),
		PROVIDER_SIGNATURES_URL: read.text('PROVIDER_SIGNATURES_URL'),
		CF_ACCOUNT_ID: read.text('CF_ACCOUNT_ID'),
		ALERT_ERROR_THRESHOLD: read.text('ALERT_ERROR_THRESHOLD'),
		ALERT_P95_THRESHOLD: read.text('ALERT_P95_THRESHOLD'),
		ALERT_BATCH_P95_THRESHOLD: read.text('ALERT_BATCH_P95_THRESHOLD'),
		ALERT_RATE_LIMIT_THRESHOLD: read.text('ALERT_RATE_LIMIT_THRESHOLD'),
		ALERT_LOOKBACK_MINUTES: read.text('ALERT_LOOKBACK_MINUTES'),
		ALERT_LATENCY_LOOKBACK_MINUTES: read.text('ALERT_LATENCY_LOOKBACK_MINUTES'),
		ALERT_MIN_LATENCY_SAMPLES: read.text('ALERT_MIN_LATENCY_SAMPLES'),
		BV_WEB: read.worker('BV_WEB'),
		BV_WHOIS: read.worker('BV_WHOIS'),
		BV_INFRA_PROBE: read.worker('BV_INFRA_PROBE'),
		QUOTA_COORDINATOR: read.durableObject('QUOTA_COORDINATOR'),
		PROFILE_ACCUMULATOR: read.durableObject('PROFILE_ACCUMULATOR'),
	};
}

/**
 * Production-only bindings, named as src/index.ts's BvMcpEnv declares them. Each is rendered only when the overlay
 * provides it, so the set the overlay actually carries is exactly what deploys.
 */
function privateBindings(read: Reader) {
	return {
		OAUTH_ISSUER: read.text('OAUTH_ISSUER'),
		REJECT_QUERY_API_KEY: read.text('REJECT_QUERY_API_KEY'),
		REQUIRE_PRODUCTION_BINDINGS: read.text('REQUIRE_PRODUCTION_BINDINGS'),
		RATE_LIMIT: read.kv('RATE_LIMIT'),
		SCAN_CACHE: read.kv('SCAN_CACHE'),
		SESSION_STORE: read.kv('SESSION_STORE'),
		MCP_ANALYTICS: read.analyticsEngineDataset('MCP_ANALYTICS'),
		TENANT_REGISTRY_DB: read.d1('TENANT_REGISTRY_DB'),
		BRAND_AUDIT_DB: read.d1('BRAND_AUDIT_DB'),
		INTELLIGENCE_DB: read.d1('INTELLIGENCE_DB'),
		SCAN_SCHEDULE_DB: read.d1('SCAN_SCHEDULE_DB'),
		MCP_ACCESS_LOG_ARCHIVE: read.r2('MCP_ACCESS_LOG_ARCHIVE'),
		BRAND_REPORTS: read.r2('BRAND_REPORTS'),
		BV_SCANNER_QUEUE: read.queue('BV_SCANNER_QUEUE'),
		BV_SCANNER_SLOW_QUEUE: read.queue('BV_SCANNER_SLOW_QUEUE'),
		MCP_ANALYTICS_QUEUE: read.queue('MCP_ANALYTICS_QUEUE'),
		BRAND_AUDIT_QUEUE: read.queue('BRAND_AUDIT_QUEUE'),
		BRAND_AUDIT_PDF_QUEUE: read.queue('BRAND_AUDIT_PDF_QUEUE'),
		ASYNC_BATCH_QUEUE: read.queue('ASYNC_BATCH_QUEUE'),
		BV_CERTSTREAM: read.worker('BV_CERTSTREAM'),
		BV_BROWSER_RENDERER: read.worker('BV_BROWSER_RENDERER'),
		BV_INFRA_GRAPH: read.worker('BV_INFRA_GRAPH'),
		BV_INTEL_GATEWAY: read.worker('BV_INTEL_GATEWAY'),
		BV_ENTERPRISE: read.worker('BV_ENTERPRISE'),
		BV_RECON: read.worker('BV_RECON'),
		BV_TLS_PROBE: read.worker('BV_TLS_PROBE'),
		// secrets.required (PRODUCTION_REQUIRED_SECRETS): the deploy refuses to ship without them.
		BV_API_KEY: read.secret('BV_API_KEY'),
		OAUTH_SIGNING_SECRET: read.secret('OAUTH_SIGNING_SECRET'),
		BV_WEB_INTERNAL_KEY: read.secret('BV_WEB_INTERNAL_KEY'),
		MCP_ACCESS_LOG_IP_ENCRYPTION_KEY: read.secret('MCP_ACCESS_LOG_IP_ENCRYPTION_KEY'),
		CF_ANALYTICS_TOKEN: read.secret('CF_ANALYTICS_TOKEN'),
	};
}

/** Public wrangler.jsonc + overlay, validated and merged exactly as scripts/inject-private-config.cjs does. */
function loadProductionSource(publicConfig: Wrangler, overlayPath: string): Wrangler {
	if (!existsSync(overlayPath)) {
		fail(`production mode requires the private overlay ${overlayPath} (template: wrangler.private.example.jsonc).`);
	}
	const overlay = parseJsonc(readFileSync(overlayPath, 'utf8'));
	for (const warning of validateOverlayKeys(overlay, publicConfig).warnings) console.warn(warning);
	const merged = mergeOverlay(publicConfig, overlay);
	const wrongVars = Object.entries(REQUIRED_PRODUCTION_VARS).filter(([name, expected]) => merged.vars?.[name] !== expected);
	if (wrongVars.length > 0) {
		fail(`unsafe production config: ${wrongVars.map(([name, expected]) => `${name} must be ${JSON.stringify(expected)}`).join('; ')}.`);
	}
	return merged;
}

function workerSettings(name: string) {
	return {
		name,
		compatibilityDate: '2026-07-29',
		compatibilityFlags: ['global_fetch_strictly_public'],
		entrypoint: 'src/index.ts',
		limits: {
			cpuMs: 300000,
		},
		observability: {
			enabled: true,
			logs: {
				headSamplingRate: 1,
				invocationLogs: false,
			},
			traces: {
				enabled: true,
				headSamplingRate: 0.01,
			},
		},
		// wrangler.jsonc tails the Worker into itself; "itself" is the -dev Worker outside production.
		tailConsumers: [{ worker: name }],
		// Replaces wrangler.jsonc's migrations v1 (QuotaCoordinator) and v2 (ProfileAccumulator), both SQLite.
		exports: {
			QuotaCoordinator: exports.durableObject({ storage: 'sqlite' }),
			ProfileAccumulator: exports.durableObject({ storage: 'sqlite' }),
		},
	};
}

export function buildCloudflareConfig({ mode, overlayPath = PRODUCTION_OVERLAY_PATH }: { mode: string | undefined; overlayPath?: string }) {
	const publicConfig: Wrangler = parseJsonc(readFileSync(PUBLIC_CONFIG_PATH, 'utf8'));
	if (mode !== 'production') {
		const read = createReader(publicConfig, NON_PRODUCTION_WORKER_NAME);
		const env = publicBindings(read);
		const workerTriggers = read.triggers();
		return {
			worker: { ...workerSettings(NON_PRODUCTION_WORKER_NAME), triggers: workerTriggers, env: { ...present(env), ...read.remainder() } },
		};
	}
	const read = createReader(loadProductionSource(publicConfig, overlayPath), PRODUCTION_WORKER_NAME);
	const env = { ...publicBindings(read), ...privateBindings(read) };
	const workerTriggers = read.triggers();
	return { worker: { ...workerSettings(PRODUCTION_WORKER_NAME), triggers: workerTriggers, env: { ...present(env), ...read.remainder() } } };
}

export default defineConfig(({ mode }) =>
	buildCloudflareConfig({ mode, overlayPath: process.env[OVERLAY_PATH_ENV] || PRODUCTION_OVERLAY_PATH }),
);
