// Generated by `cf migrate wrangler.jsonc --bundler wrangler` from the repo-root wrangler.infra-probe.jsonc.
// That root jsonc is RETAINED as the rollback config (`npx wrangler rollback --config wrangler.infra-probe.jsonc`)
// and as the sidecar drift gate's read path until the follow-up retires it — keep name + compatibilityDate in sync.
import { defineConfig } from 'cf/config';

export default defineConfig({
	worker: {
		name: 'bv-infra-probe',
		compatibilityDate: '2026-07-29',
		compatibilityFlags: ['global_fetch_strictly_public'],
		entrypoint: '../../src/workers/infra-probe.ts',
		workersDev: false,
		previewUrls: false,
		observability: {
			enabled: true,
			logs: {
				headSamplingRate: 1,
				invocationLogs: false,
			},
		},
	},
});
