// Generated by `cf migrate wrangler.jsonc --bundler wrangler` from the repo-root wrangler.infra-probe.jsonc.
// That root jsonc is now retired (SQ-240). Rollback: `npx wrangler rollback --name bv-infra-probe`.
// The sidecar drift gate reads this Worker via the --name pinned in scripts/sidecar-deploy-drift.ts.
// Keep name + compatibilityDate in sync (enforced by test/audits/infra-probe-wrangler.audit.test.ts).
import { defineConfig } from 'cf/config';

export default defineConfig({
	worker: {
		name: 'bv-infra-probe',
		compatibilityDate: '2026-07-29',
		compatibilityFlags: ['global_fetch_strictly_public'],
		entrypoint: '../../src/workers/infra-probe.ts',
		workersDev: false,
		previewUrls: false,
		observability: {
			enabled: true,
			logs: {
				headSamplingRate: 1,
				invocationLogs: false,
			},
		},
	},
});
