// SPDX-License-Identifier: BUSL-1.1
//
// Contract for scripts/ci/cf-binding-diff.mjs (SQ-262): `npm run check:cf-binding-parity` compares the cf build's
// worker.config.json with the injector's wrangler.production.jsonc and must (a) report NOTHING for identical configs
// — the ad-hoc jq it replaces gave a 70-vs-122-line diff on identical input, SQ-257 seam 9 — and (b) exit non-zero
// for any binding or trigger difference. Node pool: it spawns the real script over fixture files in a temp dir.

import { spawnSync } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { compareConfigs } from '../../scripts/ci/cf-binding-diff.mjs';

// eslint-disable-next-line @typescript-eslint/no-explicit-any -- fixture objects are mutated through arbitrary nested paths
type Json = Record<string, any>;

const scriptPath = join(process.cwd(), 'scripts/ci/cf-binding-diff.mjs');
const SECRET_URL = 'https://hooks.example.test/services/T000/B000/very-secret-token';

/** wrangler.production.jsonc as the injector writes it: JSONC (comments), every binding family, DO migrations. */
const WRANGLER_JSONC = `// Generated by scripts/inject-private-config.cjs — do not edit.
{
  "$schema": "./node_modules/wrangler/config-schema.json",
  "name": "bv-dns-security-mcp",
  "main": "src/index.ts",
  /* block comment */
  "compatibility_date": "2026-07-29",
  "compatibility_flags": ["global_fetch_strictly_public"],
  "upload_source_maps": true,
  "limits": { "cpu_ms": 300000 },
  "durable_objects": {
    "bindings": [
      { "name": "QUOTA_COORDINATOR", "class_name": "QuotaCoordinator" },
      { "name": "PROFILE_ACCUMULATOR", "class_name": "ProfileAccumulator" }
    ]
  },
  "migrations": [
    { "tag": "v1", "new_sqlite_classes": ["QuotaCoordinator"] },
    { "tag": "v2", "new_sqlite_classes": ["ProfileAccumulator"] },
    { "tag": "v3" }
  ],
  "observability": {
    "enabled": true,
    "logs": { "head_sampling_rate": 1, "invocation_logs": false },
    "traces": { "enabled": true, "head_sampling_rate": 0.01 }
  },
  "triggers": { "crons": ["*/15 * * * *", "0 8 * * *"] },
  "tail_consumers": [{ "service": "bv-dns-security-mcp" }],
  "vars": {
    "OAUTH_ISSUER": "https://dns-mcp.blackveilsecurity.com",
    "ALERT_WEBHOOK_URL": "${SECRET_URL}",
    "ALERT_ERROR_THRESHOLD": "5"
  },
  "kv_namespaces": [
    { "binding": "RATE_LIMIT", "id": "kv-rate-limit-id" },
    { "binding": "SCAN_CACHE", "id": "kv-scan-cache-id" }
  ],
  "analytics_engine_datasets": [{ "binding": "MCP_ANALYTICS", "dataset": "bv_dns_security_mcp" }],
  "d1_databases": [
    { "binding": "TENANT_REGISTRY_DB", "database_name": "tenant-registry", "database_id": "d1-reg-id", "migrations_dir": "migrations/registry" },
    { "binding": "TENANT_DB_ACME", "database_name": "tenant-acme", "database_id": "d1-acme-id" }
  ],
  "r2_buckets": [{ "binding": "MCP_ACCESS_LOG_ARCHIVE", "bucket_name": "arch", "jurisdiction": "eu" }],
  "queues": {
    "producers": [
      { "binding": "BV_SCANNER_QUEUE", "queue": "bv-scanner-queue" },
      { "binding": "BV_SCANNER_SLOW_QUEUE", "queue": "bv-scanner-slow-queue", "delivery_delay": 7 }
    ],
    "consumers": [
      {
        "queue": "bv-scanner-queue",
        "max_batch_size": 25,
        "max_batch_timeout": 5,
        "max_retries": 3,
        "dead_letter_queue": "bv-scanner-dlq",
        "max_concurrency": 4,
        "retry_delay": 30
      },
      { "queue": "bv-scanner-slow-queue", "max_batch_size": 1, "max_retries": 5, "dead_letter_queue": "dlq2" }
    ]
  },
  "services": [
    { "binding": "BV_WEB", "service": "bv-web-prod" },
    { "binding": "BV_INTEL_GATEWAY", "service": "bv-intel-gateway", "entrypoint": "Gateway", "props": { "a": 1 } }
  ],
  "secrets": { "required": ["OAUTH_SIGNING_SECRET", "BV_WEB_INTERNAL_KEY"] }
}
`;

/** The cf build's worker.config.json for the SAME deployment: `env` is keyed by BINDING name (not resource name). */
function cfFixture(): Json {
	return {
		name: 'bv-dns-security-mcp',
		compatibilityDate: '2026-07-29',
		compatibilityFlags: ['global_fetch_strictly_public'],
		triggers: [
			{ type: 'scheduled', schedule: '*/15 * * * *' },
			{ type: 'scheduled', schedule: '0 8 * * *' },
			{
				type: 'queue',
				name: 'bv-scanner-queue',
				deadLetterQueue: 'bv-scanner-dlq',
				maxBatchSize: 25,
				maxBatchTimeout: 5,
				maxConcurrency: 4,
				maxRetries: 3,
				retryDelay: 30,
			},
			{ type: 'queue', name: 'bv-scanner-slow-queue', deadLetterQueue: 'dlq2', maxBatchSize: 1, maxRetries: 5 },
		],
		tailConsumers: [{ worker: 'bv-dns-security-mcp' }],
		limits: { cpuMs: 300000 },
		observability: {
			enabled: true,
			logs: { headSamplingRate: 1, invocationLogs: false },
			traces: { enabled: true, headSamplingRate: 0.01 },
		},
		env: {
			OAUTH_ISSUER: { type: 'text', value: 'https://dns-mcp.blackveilsecurity.com' },
			ALERT_WEBHOOK_URL: { type: 'text', value: SECRET_URL },
			ALERT_ERROR_THRESHOLD: { type: 'text', value: '5' },
			QUOTA_COORDINATOR: { type: 'durable-object', worker: 'bv-dns-security-mcp', exportName: 'QuotaCoordinator' },
			PROFILE_ACCUMULATOR: { type: 'durable-object', worker: 'bv-dns-security-mcp', exportName: 'ProfileAccumulator' },
			RATE_LIMIT: { type: 'kv', id: 'kv-rate-limit-id' },
			SCAN_CACHE: { type: 'kv', id: 'kv-scan-cache-id' },
			MCP_ANALYTICS: { type: 'analytics-engine-dataset', name: 'bv_dns_security_mcp' },
			TENANT_REGISTRY_DB: { type: 'd1', name: 'tenant-registry', id: 'd1-reg-id' },
			TENANT_DB_ACME: { type: 'd1', name: 'tenant-acme', id: 'd1-acme-id' },
			MCP_ACCESS_LOG_ARCHIVE: { type: 'r2', name: 'arch', jurisdiction: 'eu' },
			BV_SCANNER_QUEUE: { type: 'queue', name: 'bv-scanner-queue' },
			BV_SCANNER_SLOW_QUEUE: { type: 'queue', name: 'bv-scanner-slow-queue', deliveryDelay: 7 },
			BV_WEB: { type: 'worker', worker: 'bv-web-prod' },
			BV_INTEL_GATEWAY: { type: 'worker', worker: 'bv-intel-gateway', exportName: 'Gateway', props: { a: 1 } },
			OAUTH_SIGNING_SECRET: { type: 'secret' },
			BV_WEB_INTERNAL_KEY: { type: 'secret' },
		},
		exports: {
			QuotaCoordinator: { type: 'durable-object', storage: 'sqlite' },
			ProfileAccumulator: { type: 'durable-object', storage: 'sqlite' },
		},
		manifest: { type: 'complete', mainModule: 'index.js', modules: { 'index.js': { type: 'esm' } } },
	};
}

let dir: string;
let caseNo = 0;

beforeAll(() => {
	dir = mkdtempSync(join(tmpdir(), 'cf-binding-diff-'));
});
afterAll(() => {
	rmSync(dir, { recursive: true, force: true });
});

/** Write the pair to fresh files and run the real CLI over them. */
function run(wrangler: string = WRANGLER_JSONC, cf: unknown = cfFixture(), extraArgs: string[] = []) {
	caseNo += 1;
	const wranglerPath = join(dir, `wrangler.production.${caseNo}.jsonc`);
	const cfPath = join(dir, `worker.config.${caseNo}.json`);
	writeFileSync(wranglerPath, wrangler);
	writeFileSync(cfPath, typeof cf === 'string' ? cf : JSON.stringify(cf));
	return spawnSync(process.execPath, [scriptPath, '--wrangler', wranglerPath, '--cf', cfPath, ...extraArgs], { encoding: 'utf8' });
}

/** The fixture wrangler config as an object, to mutate and re-serialise. */
function wranglerObject(): Json {
	return JSON.parse(
		WRANGLER_JSONC.split('\n')
			.filter((line) => !line.trimStart().startsWith('//') && !line.trimStart().startsWith('/*'))
			.join('\n'),
	);
}

describe('cf-binding-diff: identical configs', () => {
	it('exits 0 and reports parity (the reviewer false-positive case: identical configs must not diff)', () => {
		const result = run();
		expect(result.stderr).toBe('');
		expect(result.status).toBe(0);
		expect(result.stdout).toContain('cf-binding-parity: OK');
		// 3 vars + 2 kv + AE + 2 d1 + r2 + 2 queue producers + 2 workers + 2 DO + 2 secrets = 17 bindings.
		expect(result.stdout).toContain('17 bindings, 4 triggers, 2 Durable Object classes');
	});

	it('treats wrangler migrations vs cf exports as the one expected representation difference', () => {
		const wrangler = wranglerObject();
		expect(wrangler.migrations).toBeDefined();
		expect(cfFixture().exports).toBeDefined();
		expect(compareConfigs(wrangler, cfFixture())).toEqual([]);
	});

	it('is order-insensitive on both sides', () => {
		const cf = cfFixture();
		cf.triggers.reverse();
		cf.env = Object.fromEntries(Object.entries(cf.env).reverse());
		const wrangler = wranglerObject();
		wrangler.kv_namespaces.reverse();
		wrangler.triggers.crons.reverse();
		expect(run(JSON.stringify(wrangler), cf).status).toBe(0);
	});
});

describe('cf-binding-diff: any real difference exits non-zero', () => {
	it('one dropped var', () => {
		const cf = cfFixture();
		delete cf.env.ALERT_ERROR_THRESHOLD;
		const result = run(WRANGLER_JSONC, cf);
		expect(result.status).toBe(1);
		expect(result.stderr).toContain('only in wrangler.production.jsonc: binding ALERT_ERROR_THRESHOLD');
	});

	it('one changed KV id', () => {
		const cf = cfFixture();
		cf.env.SCAN_CACHE.id = 'kv-some-other-id';
		const result = run(WRANGLER_JSONC, cf);
		expect(result.status).toBe(1);
		expect(result.stderr).toContain('differs: binding SCAN_CACHE');
		expect(result.stderr).toContain('kv-scan-cache-id');
		expect(result.stderr).toContain('kv-some-other-id');
	});

	it('one changed queue max_retries', () => {
		const cf = cfFixture();
		cf.triggers.find((t: Json) => t.name === 'bv-scanner-queue').maxRetries = 10;
		const result = run(WRANGLER_JSONC, cf);
		expect(result.status).toBe(1);
		expect(result.stderr).toContain('differs: trigger queue consumer bv-scanner-queue');
		expect(result.stderr).toContain('"maxRetries":10');
	});

	it('a dropped cron, a changed DLQ, a changed D1 id, a dropped binding the cf side added', () => {
		for (const mutate of [
			(cf: Json) => cf.triggers.splice(0, 1),
			(cf: Json) => (cf.triggers.find((t: Json) => t.name === 'bv-scanner-slow-queue').deadLetterQueue = 'other-dlq'),
			(cf: Json) => (cf.env.TENANT_DB_ACME.id = 'd1-other'),
			(cf: Json) => (cf.env.EXTRA_BINDING = { type: 'kv', id: 'x' }),
		]) {
			const cf = cfFixture();
			mutate(cf);
			expect(run(WRANGLER_JSONC, cf).status).toBe(1);
		}
	});

	it('binding options that a name+id compare would miss: R2 jurisdiction, service entrypoint, DO export, producer delay', () => {
		for (const mutate of [
			(cf: Json) => (cf.env.MCP_ACCESS_LOG_ARCHIVE.jurisdiction = 'fedramp'),
			(cf: Json) => (cf.env.BV_INTEL_GATEWAY.exportName = 'Other'),
			(cf: Json) => (cf.env.BV_SCANNER_SLOW_QUEUE.deliveryDelay = 9),
			(cf: Json) => (cf.env.QUOTA_COORDINATOR.exportName = 'Renamed'),
		]) {
			const cf = cfFixture();
			mutate(cf);
			expect(run(WRANGLER_JSONC, cf).status).toBe(1);
		}
	});

	it('a Durable Object class dropped from cf exports (the migrations -> exports comparison is real, not skipped)', () => {
		const cf = cfFixture();
		delete cf.exports.ProfileAccumulator;
		const result = run(WRANGLER_JSONC, cf);
		expect(result.status).toBe(1);
		expect(result.stderr).toContain('durable object class ProfileAccumulator');
	});

	it('a var that shadows a binding of the same name (SQ-257 seam 8): both survive on the wrangler side, only one in cf', () => {
		const wrangler = wranglerObject();
		wrangler.vars.RATE_LIMIT = 'shadow';
		const cf = cfFixture();
		cf.env.RATE_LIMIT = { type: 'text', value: 'shadow' };
		const result = run(JSON.stringify(wrangler), cf);
		expect(result.status).toBe(1);
		expect(result.stderr).toContain('differs: binding RATE_LIMIT');
	});

	it('a top-level key neither normaliser understands is a failure, never silently skipped', () => {
		const wrangler = wranglerObject();
		wrangler.hyperdrive = [{ binding: 'HD', id: 'x' }];
		expect(run(JSON.stringify(wrangler)).stderr).toContain('unmapped wrangler key hyperdrive');
		const cf = cfFixture();
		cf.placement = { mode: 'smart' };
		expect(run(WRANGLER_JSONC, cf).stderr).toContain('unmapped cf key placement');
		const result = run(WRANGLER_JSONC, { ...cfFixture(), env: { ...cfFixture().env, VEC: { type: 'vectorize', name: 'v' } } });
		expect(result.status).toBe(1);
		expect(result.stderr).toContain('binding VEC');
	});
});

describe('cf-binding-diff: output hygiene and input errors', () => {
	it('never prints a text var value, even in a diff line for that var (a var can hold a webhook URL)', () => {
		const cf = cfFixture();
		cf.env.ALERT_WEBHOOK_URL.value = `${SECRET_URL}-changed`;
		const result = run(WRANGLER_JSONC, cf);
		expect(result.status).toBe(1);
		expect(result.stderr).toContain('differs: binding ALERT_WEBHOOK_URL');
		expect(result.stderr).toContain('sha256:');
		expect(result.stderr).not.toContain('very-secret-token');
		expect(result.stdout).not.toContain('very-secret-token');
	});

	it('exits 2 (not 0, not 1) when an input is missing or unparseable', () => {
		const missing = spawnSync(process.execPath, [scriptPath, '--wrangler', join(dir, 'nope.jsonc'), '--cf', join(dir, 'nope.json')], {
			encoding: 'utf8',
		});
		expect(missing.status).toBe(2);
		expect(missing.stderr).toContain('Cannot read');
		expect(run(WRANGLER_JSONC, '{ not json').status).toBe(2);
		expect(run('not json at all').status).toBe(2);
	});

	it('exits 2 on an unknown argument', () => {
		expect(run(WRANGLER_JSONC, cfFixture(), ['--bogus']).status).toBe(2);
	});
});
