// Generated by `cf migrate wrangler.jsonc --bundler wrangler` from packages/bv-whois/wrangler.jsonc, then hand-checked.
// This file is the deploy config: `npm -w packages/bv-whois run deploy` (`cf deploy`). Rollback: `npx wrangler rollback --name bv-whois`.
// The sidecar drift gate reads this Worker via an explicit `--name` (scripts/sidecar-deploy-drift.ts).
// wrangler.jsonc stays alongside as the TEST-ONLY config (cloudflareTest's `wrangler.configPath` cannot load a cf config); parity between the two
// (name, compatibilityDate, both flags, KV binding + id, workersDev/previewUrls) is asserted by test/audits/infra-probe-wrangler.audit.test.ts.
import { bindings, defineConfig } from 'cf/config';

export default defineConfig({
	worker: {
		name: 'bv-whois',
		compatibilityDate: '2026-07-29',
		compatibilityFlags: ['global_fetch_strictly_public', 'nodejs_compat'],
		entrypoint: 'src/index.ts',
		workersDev: false,
		previewUrls: false,
		observability: {
			enabled: true,
		},
		env: {
			// Public namespace id, identical to packages/bv-whois/wrangler.jsonc (that path is allowlisted in .gitleaks.toml; this one is not).
			WHOIS_CACHE: bindings.kv({ id: 'e87e50ee6c184d93bb298a1267ed5f58' }), // gitleaks:allow
		},
	},
});
