// SPDX-License-Identifier: BUSL-1.1

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { TOOLS } from '../src/schemas/tool-definitions';

type RustPermissionMode = 'ReadOnly' | 'WorkspaceWrite' | 'DangerFullAccess';

const OUTPUT = resolve('crates/bv-wasm-core/src/generated_tool_permissions.rs');

function modeForTool(tool: (typeof TOOLS)[number]): RustPermissionMode {
	if (tool.annotations.destructiveHint) return 'DangerFullAccess';
	if (tool.annotations.readOnlyHint) return 'ReadOnly';
	return 'WorkspaceWrite';
}

function render(): string {
	const arms = [...TOOLS]
		.sort((a, b) => a.name.localeCompare(b.name))
		.map((tool) => `        "${tool.name}" => PermissionMode::${modeForTool(tool)},`)
		.join('\n');

	return `// SPDX-License-Identifier: BUSL-1.1
// @generated by scripts/generate-wasm-permissions.ts

use crate::PermissionMode;

pub fn required_mode_for_tool(tool: &str) -> PermissionMode {
    match tool {
${arms}
        _ => PermissionMode::DangerFullAccess,
    }
}
`;
}

const next = render();

if (process.argv.includes('--check')) {
	const current = readFileSync(OUTPUT, 'utf8');
	if (current !== next) {
		throw new Error(`${OUTPUT} is stale. Run npm run generate:wasm-permissions.`);
	}
} else {
	writeFileSync(OUTPUT, next);
}
